Update rpi_syncroniser_from_axis_version2

diff --git a/rpi_syncroniser_from_axis_version2 b/rpi_syncroniser_from_axis_version2
--- a/rpi_syncroniser_from_axis_version2
+++ b/rpi_syncroniser_from_axis_version2
@@ -29,63 +29,51 @@ function usage() {
 }
 
 function no_multiple_instance(){
-
-		if [ "$(pgrep -x $(basename $0))" != "$$" ]; then
-			echo 'only one instance is allowed'
-			exit 1
-		fi
+	if [ "$(pgrep -x $(basename $0))" != "$$" ]; then
+		echo 'only one instance is allowed'
+		exit 1
+	fi
 }
 
 function is_external_hdd(){
-	
-		ls $LOCAL_FOLDER >/dev/null
-		
-		if [ $? -ne 0 ];then
-			echo 'there is no HDD attached'
-			exit 2
-		fi
+	ls $LOCAL_FOLDER >/dev/null
+	if [ $? -ne 0 ];then
+		echo 'there is no HDD attached'
+		exit 2
+	fi
 }
 
 function is_axis(){
-
-		ping -c 1 $AXIS_IP
-		if [ $? -ne 0 ];then
-			echo "axis server is not available..."
-			exit 3
-		fi
-	
+	ping -c 1 $AXIS_IP
+	if [ $? -ne 0 ];then
+		echo "axis server is not available..."
+		exit 3
+	fi
 }
 
 function syncronising(){
-		
-		wget -m --timeout=10 --tries=3 --user=$USER --password=$PASS ftp://$AXIS_IP:$AXIS_PORT/$AXIS_SD --directory-prefix=$LOCAL_FOLDER --reject "*.xml, *.db"
-
-		if [ $? -ne 0 ];then
-			echo 'could not download from server'
-			exit 4
-		fi
-
+	wget -m --timeout=10 --tries=3 --user=$USER --password=$PASS ftp://$AXIS_IP:$AXIS_PORT/$AXIS_SD --directory-prefix=$LOCAL_FOLDER --reject "*.xml, *.db"
+	if [ $? -ne 0 ];then
+		echo 'could not download from server'
+		exit 4
+	fi
 }
 
 function delete_oldest_folder(){
   	cd $LOCAL_FOLDER
   	if [ "$SPACE" -ge "$MAX" ];then
-  		rm -rf `ls -t | tail -n 1`
+		rm -rf `ls -t | tail -n 1`
   	fi
 }
 	
 
 function hdd_full(){
-		
-		if [ "$SPACE" -ge "99" ];then
-			exit 6
-		fi
+	if [ "$SPACE" -ge "99" ];then
+		exit 6
+	fi
 }
 
-
-
 function arranging(){
-
 	mkdir -p $TO_FOLDER
 	cd $TO_FOLDER
 
