Update rpi_syncer_from_axis

diff --git a/rpi_syncer_from_axis b/rpi_syncer_from_axis
--- a/rpi_syncer_from_axis
+++ b/rpi_syncer_from_axis
@@ -21,15 +21,20 @@ fi
 
 SPACE=`df -h | tr -d "%" | awk '/sda/ { print $5 }'`
 
+if [ "$SPACE" -ge "97" ];then
+	echo `date +%Y-%m-%d_%H:%M` 'hdd is 97 % full' >> error.log
+fi
+
 if [ "$SPACE" -ge "98" ];then
-	
-	echo 'hdd is 98 % full' > error_`date +%Y-%m-%d_%H_%M`.log
+	rm -rf `find $LOCAL_FOLDER ! -type d -name *.mp4 -printf "%T@ %p\n" | sort -n | head -n 1`
+	echo `date +%Y-%m-%d_%H:%M` 'hdd is 98 % full, the oldest files have been deleted' >> error.log
+	exit 1
 fi
 
 if [ "$SPACE" -ge "99" ];then
-	rm -rf `find $LOCAL_FOLDER ! -type d -name *.mp4 -printf "%T@ %p\n" | sort -n | head -n 1`
 	exit 1
 fi
+
 }
 
 # downloads mp4s from AXIS:
