Update arranger

diff --git a/axis/arranger b/axis/arranger
--- a/axis/arranger
+++ b/axis/arranger
@@ -1,31 +1,1 @@
-#!/bin/bash
-
-FOLDER=$1
-
-WORK_FOLDER="/share/$FOLDER/"
-ARRANGED_FOLDER="/share/$FOLDER/videos_by_day"
-EXTENSION="mkv"
-
-if [ "$#" -eq 0 ]; then  
-	echo '[-] You need add an argument folder! ex.:'
-	echo './arranger <folder>'
-	/sbin/write_log "$ arranger needs a folder as argument" 1
-	exit 1 
-fi 
-
-for i in $(find "$WORK_FOLDER" -type f -name *."$EXTENSION"); do
-	DAY=$(echo "$i" | awk -F '/' '{print $8}' | awk -F '_' '{print $1}' | sort | uniq)
-	
-	if [ ! -d "/$ARRANGED_FOLDER/$DAY" ]; then
-			mkdir -p /"$ARRANGED_FOLDER"/"$DAY"
-	fi
-	
-	cd "$ARRANGED_FOLDER"/"$DAY"
-	
-	if ! ln -sfn "$i"; then
-			echo "[-] Error: Could not create symbolic links"
-	fi
-	
-done
-/sbin/write_log "$1 arranger was succesful" 4
-exit 0
+#!/bin/bashFOLDER=$1WORK_FOLDER="/share/$FOLDER/"ARRANGED_FOLDER="/share/$FOLDER/videos_by_day"if [ "$#" -eq 0 ]; then   echo '[-] You need add an argument folder! ex.:' echo './arranger <folder>' /sbin/write_log "$ arranger script needs a folder as an argument" 1 exit 1 fi for i in $(find "$WORK_FOLDER" -type f -name *.mkv); do DAY=$(echo "$i" | awk -F '/' '{print $8}' | awk -F '_' '{print $1}' | sort | uniq)  if [ ! -d "/$ARRANGED_FOLDER/$DAY" ]; then   mkdir -p /"$ARRANGED_FOLDER"/"$DAY" fi  cd "$ARRANGED_FOLDER"/"$DAY"  if ! ln -sfn "$i"; then   echo "[-] Error: Could not create symbolic links"   /sbin/write_log "$ arranger script couldn't create symbolic links" 1 fi done/sbin/write_log "$1 arranger finished" 4exit 0
